text2other_instructions = {
    "audio": [
        "Develop a sound with the given text.",
        "Incorporate sonorities from the text into an audio.",
        "Create a soundscape based on the provided text.",
        "Formulate a comprehensive sound using the words in this text.",
        "Implement an audio from the written material.",
        "Engineer a sonic representation of this text.",
        "Generate a soundscape of this text.",
        "Can you generate a sound from this passage?",
        "Compose a novel audio out of this content.",
        "Could you craft a noise reliant on the text?",
        "Generate a noise for this text.",
        "Would you be able to make a sound from the text?",
        "Compile an audio indulging the written text.",
        "Do you think you can arrange a sound from the text?",
        "Generate a sound made from the text.",
        "Design a sound that doubles the text.",
        "Make an audio with this text as a source.",
        "Compose a new audio based on this text.",
        "Is it possible to form a sound utilizing this text?",
        "Could you conjure a sound under the influence of this text?",
        "Can you fashion a tune with the text in it?",
        "Come up with a sound with this text as its foundation.",
        "Develop an audio rooted in the information provided.",
        "Create a melodic tone of the text.",
        "Synthesize a catchy rhythm for the text.",
        "Can you develop a noise reflective of the text?",
        "Are you able to craft a sound dependent on the text?",
        "Could you assemble a sound that reflects the given text?",
        "Generate a buzzing atmosphere with the text.",
        "Come up with a harmonic resonance from the text.",
        "Create an aural interpretation from the content.",
        "Generate a quiet reverberation due to the text.",
        "Make a sweeping soundscape with the words in it.",
        "Do you think you can construct a sound out of this passage?",
        "Formulate a captivating soundscape of the text.",
        "Produce a noise illustration for the written material.",
        "Generate a truly immersive sound for the source.",
        "Design a soundscape which is based on the text.",
        "Design a calm tune from the words in this passage.",
        "Construct the kind of sound from this text which would accompany an ocean wave rolling in.",
        "Make the text speak with a soft lulling noise.",
        "Is it possible to create a mid-tempo tempo with this text?",
        "Produce a low hum using the text as a source.",
        "Create a quivering sound due to the text.",
        "Can you compile a noise evoking the mood of the text?",
        "Render a pulsating echo for this given content.",
        "Come up with a soothing audio with words intertwined in it.",
        "Design a sound relying heavily on the content itself.",
        "Make a ringing sound relevant to the text.",
        "Create a tapestry of high and low notes based on the provided text.",
        "Is it possible to devise a soothing and lush soundscape from the text?",
        "Generate a sweet soundscape from the provided words.",
        "Develop a hypnotic sound induced by this text.",
        "Make a minor tune out of the words in this passage.",
        "Synthesize a sweeping sound based on the written material.",
        "Could you make a powerful sound which reflects the words in the text?",
        "Extract a properly paced sound from the written material.",
        "Design a rocking harmony from this passage of words.",
        "Compose a beautiful sound that includes the provided text.",
        "Render a sweeping tone made up of the words in the text.",
        "Can you create an amusing noise based on the content?",
        "Develop an acoustic out of this text.",
        "Make the text sound more animated through noise?",
        "Could you generate a sound which expresses the given text?",
        "Create a vibrant audio of the material provided.",
        "Synthesize a passionate sound from the words in the text.",
        "Construct a high-pitched soundscape from this text.",
        "Is it possible to arrange a joyful cacophony through the text?",
        "Make an audio of passionate intensity with the given text.",
        "Design a clattering noise originating from the text.",
        "Generate an audio which is based on the stories written within the text.",
        "Could you assemble a playful synthesis around the words in this text?",
        "Make a noise that inspires a reminiscing of the text.",
        "Can you compile a soundscape of the words in the passage?",
        "Generate a tone inspired by the aspects of the text.",
        "Could you make a sound that moves along with the information given?",
        "Manufacture a sound that comprehends this text.",
        "Make a sound containing the different elements of the text.",
        "Develop an audio which displays the text in a different form.",
        "Can you design a soundscape using the words in the passage?",
        "Construct a different sound out of the words in this text.",
        "Is it possible to create a sound that emphasizes the text's emotion?",
        "Arrange a sound that showcases its connection to the text.",
        "Can you compile an atmospheric audio that is reflective of the text?",
        "Develop a sound that could invite a reader's imagination.",
        "Fabricate a soundscaping of the text as a whole.",
        "Make a sound that illuminates the text with an engaging tone.",
        "Could you synthesize an audio that envelops the text in a different musical layer?",
        "Generate an audio that offers a unique interpretation of the text.",
    ]
}
