other2text_instructions = {
    "speech": [
        "Analyze the spoken words and transcribe them accurately.",
        "Can you please convert this speech into written text?",
        "Listen carefully and transform the spoken words into text.",
        "Provide a textual representation of the spoken content.",
        "Convert the speech into a written transcript.",
        "Recognize and write down what is being said.",
        "Generate a text version of the spoken words.",
        "Transform the spoken language into text form.",
        "Please transcribe this speech into written text.",
        "Write down the spoken words accurately.",
        "Turn the spoken words into written format.",
        "Capture the spoken content as text.",
        "Transform the speech into a textual representation.",
        "Generate a transcript of the spoken words.",
        "Provide a written version of the spoken words.",
        "Transcribe the speech for better understanding.",
        "Change the spoken language into text.",
        "Record the spoken words in textual form.",
        "Please transcribe this spoken content.",
        "Recognize the spoken words and write them down.",
        "Convert the speech into written format.",
        "Generate a textual representation of the speech.",
        "Transform the spoken words into text form.",
        "Capture the spoken content as written text.",
        "Convert the spoken language into text.",
        "Provide a transcript of the spoken words.",
        "Convert the speech into a written document.",
        "Recognize and write out what is being said.",
        "Please transform this speech into written text.",
        "Generate a text version of the spoken content.",
        "Transform the spoken language into text form.",
        "Capture the spoken content as a transcript.",
        "Provide a textual representation of the speech.",
        "Transcribe the spoken words with precision.",
        "Convert the speech into a written transcript.",
        "Recognize and transcribe the spoken content.",
        "Write down the spoken words accurately.",
        "Change the spoken language into text.",
        "Generate a transcript of the spoken words.",
        "Capture the spoken content as written text.",
        "Transform the speech into a textual representation.",
        "Recognize the speech and write it out.",
        "Convert the spoken words into written format.",
        "Write down what you hear in the speech.",
        "Transcribe the speech for better understanding.",
        "Convert the spoken language into text.",
        "Record the spoken words in textual form.",
        "Please transcribe this spoken content accurately.",
        "Recognize the spoken words and transcribe them.",
        "Convert the speech into a text document.",
        "Generate a text version of the spoken content.",
        "Capture the spoken content as text.",
        "Convert the spoken language into written format.",
        "Provide a transcript of the spoken words.",
        "Convert the speech into a written script.",
        "Recognize and write out what is being spoken.",
        "Transform the spoken words into text format.",
        "Change the spoken language into written text.",
        "Generate a textual representation of the speech.",
        "Transform the speech into written format.",
        "Capture the spoken content as a transcript.",
        "Provide a written version of the spoken words.",
        "Transcribe the spoken words accurately.",
        "Convert the speech into a written transcript.",
        "Write down the spoken words clearly.",
        "Convert the spoken language into text form.",
        "Generate a transcript of the spoken words.",
        "Capture the spoken content as written text.",
        "Transform the speech into a textual representation.",
        "Recognize the speech and write it down.",
        "Convert the spoken words into written form.",
        "Write down what you hear in the speech.",
        "Transcribe the speech for better understanding.",
        "Convert the spoken language into text.",
        "Record the spoken words as text.",
        "Please transcribe this spoken content clearly.",
        "Recognize the spoken words and transcribe them accurately.",
        "Convert the speech into a text document.",
        "Generate a text version of the spoken content.",
        "Capture the spoken content as text.",
        "Convert the spoken language into written format.",
        "Provide a transcript of the spoken words.",
        "Convert the speech into a written transcript.",
        "Recognize and write out what is being spoken.",
        "Transform the spoken words into text format.",
        "Change the spoken language into written text.",
        "Generate a textual representation of the speech.",
        "Transform the speech into written format.",
        "Capture the spoken content as a transcript.",
        "Provide a written version of the spoken words.",
        "Transcribe the spoken words accurately.",
        "Convert the speech into a written script.",
        "Write down the spoken words clearly.",
        "Convert the spoken language into text form.",
        "Generate a transcript of the spoken words.",
        "Capture the spoken content as written text.",
        "Transform the speech into a textual representation.",
        "Recognize the speech and write it down.",
        "Convert the spoken words into written form.",
        "Write down what you hear in the speech.",
        "Transcribe the speech for better understanding.",
        "Convert the spoken language into text.",
        "Record the spoken words as text.",
        "Please transcribe this spoken content clearly.",
        "Recognize the spoken words and transcribe them accurately.",
        "Convert the speech into a text document.",
        "Generate a text version of the spoken content.",
        "Capture the spoken content as text.",
        "Convert the spoken language into written format.",
        "Provide a transcript of the spoken words.",
        "Convert the speech into a written transcript.",
        "Recognize and write out what is being spoken.",
        "Transform the spoken words into text format.",
        "Change the spoken language into written text.",
        "Generate a textual representation of the speech.",
        "Transform the speech into written format.",
        "Capture the spoken content as a transcript.",
        "Provide a written version of the spoken words.",
        "Transcribe the spoken words accurately.",
        "Convert the speech into a written script.",
        "Write down the spoken words clearly.",
        "Convert the spoken language into text form.",
        "Generate a transcript of the spoken words.",
        "Capture the spoken content as written text.",
        "Transform the speech into a textual representation.",
        "Recognize the speech and write it down.",
        "Convert the spoken words into written form.",
        "Write down what you hear in the speech.",
        "Transcribe the speech for better understanding.",
        "Convert the spoken language into text.",
        "Record the spoken words as text.",
        "Please transcribe this spoken content clearly.",
        "Recognize the spoken words and transcribe them accurately.",
        "Convert the speech into a text document.",
        "Generate a text version of the spoken content.",
        "Capture the spoken content as text.",
        "Convert the spoken language into written format.",
        "Provide a transcript of the spoken words.",
        "Convert the speech into a written transcript.",
        "Recognize and write out what is being spoken.",
        "Transform the spoken words into text format.",
        "Change the spoken language into written text.",
        "Generate a textual representation of the speech.",
        "Transform the speech into written format.",
        "Capture the spoken content as a transcript.",
        "Provide a written version of the spoken words.",
        "Transcribe the spoken words accurately.",
        "Convert the speech into a written script.",
        "Write down the spoken words clearly.",
        "Convert the spoken language into text form.",
        "Generate a transcript of the spoken words.",
        "Capture the spoken content as written text.",
        "Transform the speech into a textual representation.",
        "Recognize the speech and write it down.",
        "Convert the spoken words into written form.",
        "Write down what you hear in the speech.",
        "Transcribe the speech for better understanding.",
        "Convert the spoken language into text.",
        "Record the spoken words as text.",
        "Please transcribe this spoken content clearly.",
        "Recognize the spoken words and transcribe them accurately.",
        "Convert the speech into a text document.",
        "Generate a text version of the spoken content.",
        "Capture the spoken content as text.",
        "Convert the spoken language into written format.",
        "Provide a transcript of the spoken words.",
        "Convert the speech into a written transcript.",
        "Recognize and write out what is being spoken.",
        "Transform the spoken words into text format.",
        "Change the spoken language into written text.",
        "Generate a textual representation of the speech.",
        "Transform the speech into written format.",
        "Capture the spoken content as a transcript.",
        "Provide a written version of the spoken words.",
        "Transcribe the spoken words accurately.",
        "Convert the speech into a written script.",
        "Write down the spoken words clearly.",
        "Convert the spoken language into text form.",
        "Generate a transcript of the spoken words.",
        "Capture the spoken content as written text.",
        "Transform the speech into a textual representation.",
        "Recognize the speech and write it down.",
        "Convert the spoken words into written form.",
        "Write down what you hear in the speech.",
        "Transcribe the speech for better understanding.",
        "Convert the spoken language into text.",
        "Record the spoken words as text.",
        "Please transcribe this spoken content clearly.",
        "Recognize the spoken words and transcribe them accurately.",
        "Convert the speech into a text document.",
        "Generate a text version of the spoken content.",
        "Capture the spoken content as text.",
        "Convert the spoken language into written format.",
        "Provide a transcript of the spoken words.",
        "Convert the speech into a written transcript.",
        "Recognize and write out what is being spoken.",
        "Transform the spoken words into text format.",
        "Change the spoken language into written text.",
        "Generate a textual representation of the speech.",
        "Transform the speech into written format.",
        "Capture the spoken content as a transcript.",
        "Provide a written version of the spoken words.",
        "Transcribe the spoken words accurately.",
        "Convert the speech into a written script.",
        "Write down the spoken words clearly.",
        "Convert the spoken language into text form.",
        "Generate a transcript of the spoken words.",
        "Capture the spoken content as written text.",
        "Transform the speech into a textual representation.",
        "Recognize the speech and write it down.",
        "Convert the spoken words into written form.",
        "Write down what you hear in the speech.",
        "Transcribe the speech for better understanding.",
        "Convert the spoken language into text.",
        "Record the spoken words as text.",
        "Please transcribe this spoken content clearly.",
        "Recognize the spoken words and transcribe them accurately.",
        "Convert the speech into a text document.",
        "Generate a text version of the spoken content.",
        "Capture the spoken content as text.",
        "Convert the spoken language into written format.",
        "Provide a transcript of the spoken words.",
        "Convert the speech into a written transcript.",
        "Recognize and write out what is being spoken.",
        "I need you to figure out the words spoken in this recording.",
        "Could you tell me what is uttered in the next sound bite?",
        "Please figure out the words spoken in this recording.",
        "Could you discern what is uttered in the next sound bite?",
        "Please decode the words spoken in this recording.",
        "Could you unravel what is uttered in the next sound bite?",
        "I want you to identify the speech in this recording. Listen attentively.",
        "Please discern the words spoken in this sound clip.",
        "I want you to recognize the speech in this recording. Listen carefully.",
        "Please identify the words spoken in this sound clip.",
        "I want you to discern the speech in this recording. Listen attentively.",
        "Please recognize the words spoken in this sound clip.",
    ],
    "image": [
        "Describe the scene in this picture.",
        "Write a caption for this image.",
        "What do you see in this photo?",
        "Provide a brief description of the contents of this picture.",
        "Can you summarize what's happening in this image?",
        "Offer a short explanation of this photo.",
        "Write a few words to convey the essence of this image.",
        "Share your thoughts on what's depicted here.",
        "Craft a caption that captures the mood of this picture.",
        "Describe the subject matter of this photograph.",
        "What's your interpretation of this visual?",
        "Create a textual representation of this scene.",
        "Please put this image into words.",
        "Can you narrate the story behind this photo?",
        "Offer a description of what's going on in this picture.",
        "Summarize the key elements of this image.",
        "Write a sentence that conveys the emotions in this image.",
        "Describe the setting of this photograph.",
        "Provide a brief account of this visual.",
        "Share your perspective on this picture.",
        "Craft a one-sentence summary of this image.",
        "Tell me about the objects in this photo.",
        "What words would you use to depict this scene?",
        "Describe the atmosphere of this image.",
        "Offer a concise portrayal of this visual.",
        "Write a caption that encapsulates the essence of this picture.",
        "Can you elucidate what's happening here?",
        "Summarize the content of this image.",
        "Share your observations about this photograph.",
        "Describe the elements that catch your eye in this picture.",
        "Craft a short narrative for this image.",
        "Provide a brief textual overview of this scene.",
        "What stands out to you in this photo?",
        "Write a few words to encapsulate this visual.",
        "Describe the mood conveyed by this image.",
        "Offer your interpretation of the subject matter.",
        "Summarize this picture's story.",
        "Tell me about the details in this photograph.",
        "What words would you use to describe this scene?",
        "Describe the emotions evoked by this image.",
        "Write a caption that captures the essence of this visual.",
        "Can you elaborate on what's going on here?",
        "Provide a short description of this picture.",
        "Share your perspective on this photograph.",
        "Craft a sentence that tells the story of this image.",
        "Describe the elements that draw your attention in this scene.",
        "Summarize the essence of this photo.",
        "Offer your insights into this visual.",
        "Tell me about the characters in this picture.",
        "Write a brief narrative for this image.",
        "Write a brief description of what you see in this image.",
        "Can you provide a caption that captures the essence of this picture?",
        "Describe the content of this image in a sentence.",
        "Summarize the scene in this picture.",
        "Offer a verbal depiction of what's happening in this visual.",
        "Craft a caption that tells a story about this image.",
        "Please provide an interpretation of this image in words.",
        "Describe the scene portrayed in this picture.",
        "Create a text-based representation of this visual.",
        "Offer a brief narrative for this image.",
        "Write a concise caption that encapsulates this image's message.",
        "Can you verbalize what's going on in this picture?",
        "Share your thoughts on this image with a caption.",
        "Please describe the elements within this picture.",
        "Provide a textual summary of this visual.",
        "Capture the mood of this image in a sentence.",
        "Describe the setting and characters in this image.",
        "Offer a brief textual explanation of this scene.",
        "Craft a caption that conveys the emotion in this picture.",
        "Summarize the story told by this image.",
        "Write a caption that encapsulates the meaning of this visual.",
        "Share your interpretation of this image through words.",
        "Can you provide a narrative for this picture?",
        "Describe the atmosphere of this image in a sentence.",
        "Offer a verbal snapshot of what's happening here.",
        "Please provide a caption that contextualizes this image.",
        "Describe the objects and actions in this picture.",
        "Create a textual representation of this scene.",
        "Craft a caption that evokes a sense of wonder.",
        "Summarize the essence of this image in words.",
        "Offer a brief verbal commentary on this visual.",
        "Write a descriptive caption for this picture.",
        "Please convey the feelings this image invokes in you.",
        "Describe the elements that catch your eye in this image.",
        "Provide a concise summary of this scene.",
        "Capture the beauty of this image with a caption.",
        "Share your perspective on this image through words.",
        "Can you narrate what's happening in this picture?",
        "Write a brief caption that tells a story.",
        "Describe the details that stand out in this image.",
        "Offer a textual interpretation of this visual.",
        "Summarize the narrative portrayed by this image.",
        "Craft a caption that sparks curiosity.",
        "Please describe the colors and shapes in this picture.",
        "Provide a caption that conveys a sense of serenity.",
        "Write a brief narrative to accompany this image.",
        "Share your impression of this image in words.",
        "Can you provide a caption that sets the scene?",
        "Describe the people and objects in this picture.",
        "Offer a concise verbal explanation of this visual.",
        "Describe the scene depicted in this image.",
        "Provide a detailed caption for this picture.",
        "Write a brief summary of what you see in the image.",
        "Explain what's happening in this visual.",
        "Can you narrate the story behind this photograph?",
        "Give me your impressions of this image.",
        "Craft a textual representation of this picture.",
        "Offer a verbal portrayal of the contents of this image.",
        "What words come to mind when you look at this photo?",
        "Describe the elements that make up this scene.",
        "Summarize the main focal point of this image.",
        "Describe the scene in the image.",
        "Outline the image in words.",
        "Capture the mood of the image in few words.",
        "Compose a caption for the image.",
        "Create a short phrase that summarizes the content of the image.",
        "Put into words what you observe in the image.",
        "Name the main elements of the image.",
        "Suggest a title for the image.",
        "Explain visually what the picture is saying.",
        "Notice the details in the image and lend words to it.",
        "Identify the objects in the image.",
        "Narrate a story based on the image.",
        "Find the best words to describe the image.",
        "Imagine the image in full sorrow and come up with a suitable caption.",
        "Craft a one-sentence caption for the image.",
        "Detail the message of the image in words.",
        "Envisage a story-line for the image and pen it down in words.",
        "Write a story inspired by the image.",
        "Find a succinct way to characterize the image.",
        "Infer what could be the underlying meaning of the image in few words.",
        "Sketch a story or a vision analysing the image.",
        "Construct a phrase that renders the image in a few words.",
        "Make a short description of the image.",
        "Note the color, location, feelings in the image and translate in words.",
        "Are there any emotions expressed in the image? Verbally explain.",
        "Guess what these people in the image are doing.",
        "Ascertain the theme of the image.",
        "Describe the action taking place in the image.",
        "Put together a one-sentence description of what the image conveys.",
        "Does the image evoke any emotion? Describe it in words.",
        "Understand the story through the image and explain it.",
        "Give an expansive explanation of the image.",
        "Find the perfect words to express the image.",
        "Identify the colours, shapes and objects in the image.",
        "Make a narrative of the story suggested by the image.",
        "Figure out any particular emotion associated with the image.",
        "If the image was a movie, what would its story be like?",
        "Can you explain the seven-second sound of the image?",
        "Write a synopsis of the image.",
        "Utilize the fine details of the image to explain it.",
        "Analyse the components of the image and explain its narrative.",
        "Arouse an opinion about the image.",
        "Share a meaningful perspective and thoughts on the image.",
        "Construct a creative caption applicable to the image.",
        "Paint a clear picture about the image in the mind of reader.",
        "Invent a tagline for the image in words.",
        "Attach a suitable description to the nuances of the image.",
        "Visualize the state of mind of the characters in the image and explain it.",
        "Describe the story of the image in a single sentence.",
        "Describe a condition from the image.",
        "Are there any discrepancies in the image? Explain them in words.",
        "Analyse the visual composition of the image and explain.",
        "What is the primary emotion on display in the image?",
        "Do you feel something special while looking at the image? Describe it.",
        "Allude to the primary message of the image.",
        "Watershed the colour pattern of the image and describe them.",
        "Is there any etched symbolism in the image? Explain it.",
        "Find the keywords for the image and explain their significance.",
        "Capture the beauty of image in a sentence.",
        "Detect the underlying meaning of the image.",
        "Pen down the picture of the image as you see it.",
        "Identity the distinguishing features of the image and explain them.",
        "Relate the property of image with the character in it.",
        "Illustrate the message embedded in the image.",
        "Find the characters and their current state of emotion in the image.",
        "Why is the image relevant to the story? Describe it.",
        "Compose a description of the image based on its composition.",
        "Let the image speak to you and articulate it with your words.",
        "Sum up the idea of the image in a short expression.",
        "Inspect the details of the image.",
        "Find the best way to express the visual elements of the image.",
        "Seek out the central notion of the image and explain it.",
        "What could be the parallel story behind the image?",
        "Denote the scene of the image with words.",
        "Articulate the vibrancy and presence of the image.",
        "Identify the era and genre suggested by the image.",
        "Evaluate the importance of the subject in the image.",
        "Identify the items in the image and map them.",
        "Expound the thoughts, ideas and symbolism behind the image.",
        "Unveil the hidden details of the image and describe them.",
        "Look out for the message conveyed by the image.",
        "Is there any relation between the objects in the image? Explain.",
        "Recognize the basic elements, objects, and characters of the image.",
        "Reveal the tale ingrained in the image in two or three sentences.",
        "Polygonize the main characters in the image and explain.",
        "Characterize the whole image with one word.",
        "Can you detect the background of the image? Describe it.",
        "Infer the details from the image and create a vocabulary around it.",
        "Express the essence of the image with one canonical phrase.",
        "Dig deep to decipher the suppressed message of the image.",
        "Categorize the shape of the image and explain its significance.",
        "Can you make out the spatial relationship of the objects in the image?",
        "Break down the image in words and formulate a captivating caption.",
        "Build a brief story out of the image and summarize it.",
        "Inspect the associations among the objects in the image.",
        "Analyze the line, shape and form of the image and explain it.",
        "What activity could be reflecting in the image?",
        "Use descriptive words to portray the energy of the image to the reader.",
        "Compose a sentence which captures the core basis of the image.",
        "Interpret the image through a brief sketch of its contents.",
    ],
    "music": [
        "Listen to the music and describe the mood it evokes.",
        "Take a moment to describe the emotions this music makes you feel.",
        "Can you put into words the feelings this song invokes?",
        "Describe the melody and rhythm of this music.",
        "Take a few notes to describe the tone and tempo of this piece.",
        "How would you describe the genre of this music?",
        "Use your words to paint a picture of the atmosphere created by this song.",
        "What do you hear in this music: instruments, vocals, both?",
        "Take a closer look at the lyrics and describe the message they convey.",
        "Close your eyes and describe the mental images this music creates.",
        "Can you put this song into words for someone who has never heard it?",
        "What words come to mind when listening to this music?",
        "Describe the transitions between different sections of this song.",
        "Imagine yourself in a specific setting and describe how this music would fit in.",
        "Can you describe the beat and pacing of this track?",
        "Use adjectives to describe the overall energy of this music.",
        "How would you describe the vocals in this song: smooth, powerful, emotional?",
        "Describe the instrumentation and arrangement of this music.",
        "Close your eyes and describe the color palette that comes to mind while listening to this song.",
        "Take a moment to describe the layers and textures of this music.",
        "Can you put into words the cultural influences present in this piece?",
        "Describe the build-up and climax of this song.",
        "What are some unique elements of this piece that stand out to you?",
        "Share your thoughts on how the lyrics and music work together to tell a story.",
        "How would you describe the vocal range and style in this song?",
        "Take a closer listen and describe the use of dynamics and sonic effects.",
        "Can you describe the mood shifts throughout this song?",
        "Recommend a specific location or event where this music would be fitting.",
        "Use descriptive words to convey the overall message of this piece.",
        "What aspects of this music make it suitable for a particular audience?",
        "Describe the influence of different cultures or musical styles on this song.",
        "Close your eyes and describe the journey this music takes you on.",
        "Can you describe the instrumental solos or breakdowns in this piece?",
        "Discuss the use of repetition or variation in this song.",
        "Use adjectives to describe the tempo and speed of this music.",
        "What emotions or memories does this music bring up for you?",
        "Share your thoughts on the use of vocals and instrumentals in this piece.",
        "Describe how this song differs from other music in the same genre.",
        "Use sensory words to describe the sounds and textures in this music.",
        "Talk about the transitions between verses, chorus, and bridge in this song.",
        "What technical elements make this song stand out to you?",
        "Use words to describe the themes or concepts explored in this music.",
        "Share your thoughts on the overall structure and flow of this piece.",
        "What do you think was the artist's intention with this music?",
        "Use descriptive language to convey the mood and atmosphere of this song.",
        "Discuss any potential influences or inspirations for this music.",
        "What do you think the audience's reaction would be to this music?",
        "Use adjectives to describe the vocals: soulful, haunting, powerful.",
        "Share your thoughts on the use of instruments and effects in this song.",
        "Describe the connections or references to other genres in this music.",
        "Use your words to describe the songwriting and composition of this piece.",
        "Discuss the collaboration and teamwork that must have gone into creating this music.",
        "Use sensory words to describe the overall sound and production quality.",
        "Share any personal connections or experiences that this music brings up for you.",
        "Imagine yourself in the artist's shoes and describe the inspiration behind this music.",
        "Use your words to describe the melodic and harmonic structure of this song.",
        "Discuss any cultural or historical significance behind this music.",
        "Use adjectives to describe the vocal range and dynamics in this piece.",
        "Share your thoughts on the use of live instruments or electronic sounds in this music.",
        "Imagine a choreography for this music and describe its movements.",
        "Use descriptive words to portray the energy and intensity of this song.",
        "Share your perspective on how this music reflects the artist's personal journey.",
        "Use sensory language to describe the overall atmosphere and vibe of this music.",
        "Discuss any experimental or unconventional elements in this song.",
        "Use your words to convey the emotions and mood shifts in this music.",
        "Talk about the use of repetition and variation in this piece.",
        "Share your thoughts on the instrumental or vocal techniques used in this song.",
        "Describe the transitions between verses, chorus, bridge, and outro in this music.",
        "Use adjectives to describe the harmonies and textures in this piece.",
        "Imagine a music video for this song and describe the visuals.",
        "Use sensory words to convey the imagery and feelings evoked by this music.",
        "Talk about the contrast and balance between different elements in this song.",
        "Use descriptive language to describe the sonic landscape of this piece.",
        "Share your thoughts on the use of storytelling and symbolism in this music.",
        "Discuss any cultural, political, or social commentary present in this song.",
        "Use your words to describe the thematic structure of this music.",
        "Imagine yourself at a live performance of this song and describe the experience.",
        "Use adjectives to describe the instrumental solos and breakdowns in this piece.",
        "Share your thoughts on the song's structure and how it contributes to its impact.",
        "Consider the lyrics and describe the overall message of this music.",
        "Talk about the balance and complementation between vocals and instrumentals in this song.",
        "Use sensory language to describe the mood and atmosphere of this piece.",
        "Share any insights into the emotion and passion behind this music.",
        "Imagine a different artist covering this song and discuss their interpretation.",
        "Use descriptive words to convey the pacing and energy of this music.",
        "Share your thoughts on the use of symbolism and metaphors in this song.",
        "Imagine yourself attending a concert or event where this music is played and describe the scene.",
        "Use adjectives to describe how this song creates a sense of nostalgia or longing.",
        "Talk about the transitions between verses and chorus in this piece.",
        "Use your words to describe the instrumental or vocal arrangements in this music.",
        "Share your insights on the cultural or social significance of this song.",
        "Use sensory language to describe the emotions and connections in this music.",
        "Discuss the impact and relevance of this music in today's world.",
        "Use descriptive words to convey the journey and evolution of this song.",
        "Share your thoughts on the lyrics and how they relate to the music.",
        "Use your words to describe the various elements and layers of this piece.",
        "Imagine yourself collaborating with the artist and describe the creative process behind this music.",
        "Use adjectives to describe the vocal range and styles used in this song.",
        "Share any personal interpretations or meanings that this music holds for you.",
    ],
    "audio": [
        "Please report what can be heard in the background.",
        "Notice the types of sounds that can be heard in the audio.",
        "What noises are present in this audio?",
        "Is the audio filled with conversation or more abstract noises?",
        "Can you pick out any voices?",
        "Are there any other noteworthy sounds?",
        "Record what is going on in the audio.",
        "Make observations about the audio.",
        "Identify the dominant sound in the clip.",
        "Make a distinction between the sounds that are hard to distinguish.",
        "Is the audio calm?",
        "Can you hear excited words or sounds?",
        "Is the audio soft or loud?",
        "Is the sound consistent or chaotic?",
        "What type of sound is present in the audio?",
        "Can you make out any sound effects?",
        "What is the main sound that is present in the audio?",
        "Does the audio appear to contain natural sounds?",
        "Is there any point in the audio with a high pitch sound?",
        "Look out for any type of patterns in the audio.",
        "Recognize any sound that could be described as unusual.",
        "Can you detect any known words or phrases?",
        "Are there any unfamiliar or unfamiliar sounds?",
        "Record any loud noises that can be picked up.",
        "Are there any hushed sounds in the audio clip?",
        "Are there any discordant sounds?",
        "Are there any buzzing or humming sounds?",
        "Make out any types of whistling.",
        "Identify whether the audio has a low or high register.",
        "Can you detect any long continuous sounds?",
        "Are there any sudden changes in sound?",
        "List any type of echoing sounds in the clip.",
        "Can you hear the sound of laughter?",
        "Pay attention to a variety of tones in the audio.",
        "Note if there are any echoing noises.",
        "Are there any harsh sounds?",
        "Describe any tranquil sounds that are present in the clip.",
        "Analyze the type of background noise.",
        "Are there any clattering noises?",
        "Are there any bell-like sounds?",
        "Are there any rising or falling sounds?",
        "Can you detect the sound of screaming?",
        "Note any echoes in the audio clip.",
        "Make out any reverberation in the audio.",
        "Listen for any softness in the sound.",
        "Notice any vibrating sounds.",
        "Are there any metallic sounds in the clip?",
        "Can you make out any pounding sound?",
        "Take note of any drumming sounds.",
        "Is the audio full of monotonous noises?",
        "Pay attention to any paddling sound.",
        "Note any crackling noises present in the audio.",
        "Make mention of any harmonious tones.",
        "Identify any hissing sound present.",
        "Is there any whisper in the clip?",
        "Can you make out any growls?",
        "Is there any clinking sound in the background?",
        "What is the loudest sound in the audio clip?",
        "Detect any squealing noises.",
        "Pay attention to any rustling sound in the clip.",
        "Make out any screeching sounds.",
        "Note any chirping that is heard.",
        "Is there any croaking sound in the clip?",
        "Listen for any type of panting sound.",
        "Describe any bellowing noises.",
        "Are there any shrieks in the audio?",
        "Can you make out any howling noise?",
        "Notice any snoring sounds.",
        "Are there any whirring noises in the background?",
        "Do you hear any crashing sound?",
        "Are there any thumping sounds in the audio?",
        "What is the faintest sound in the clip?",
        "Can you pick out any wooing noises?",
        "Are there any honking sounds in the clip?",
        "Is there any squeaking in the audio?",
        "Note any whistles in the background.",
        "Are there any neighing sounds in the clip?",
        "Do you detect any cackling noises?",
        "Is there any singing in the audio?",
        "Make out any types of humming.",
        "Describe any yelps present in the clip.",
        "Does the audio contain any barking noise?",
        "Can you pick out any hooting sounds?",
        "Are there any purring sounds in the audio?",
        "Notice any clicking or tapping sounds.",
        "Are there any cawing noises in the clip?",
        "Can you make out any trilling sound?",
        "Are there any cooing sounds in the background?",
        "Do you detect any whooping in the audio?",
        "List any types of crooning that can be heard.",
        "Describe any buzzes in the audio clip.",
        "Can you hear the sound of moans?",
        "Are there any chattering or chirping noises?",
        "Do you detect any screechy sound in the clip?",
        "Are there any whizzing sounds in the audio?",
        "Can you hear the sound of laughter in the background?",
        "Can you pick out any rumbling or roaring sound?",
        "Are there any bell-like tones in the clip?",
        "Notice any braying noises in the audio.",
        "Make a distinction between the subtle sounds present in the clip.",
    ]
}
