text2other_instructions = {
    "speech": [
        "Would you kindly read this text out loud so that I can hear it?",
        "I need you to vocalize these written words so they can be heard audibly.",
        "Could you please give voice to this text so that it is no longer silent?",
        "It would help me tremendously if you could utter these letters into sounds.",
        "I require you to speak the words on this page aloud.",
        "Would you transform these symbols into speech using your voice?",
        "Could you change these written phrases into spoken language for me?",
        "I would appreciate it if you could translate this text into audible speech.",
        "Do me a favor and give sound to these mute letters.",
        "Is it possible for you to make this text heard by speaking it?",
        "Would you mind articulating these words vocally for me to hear?",
        "Can you say these written words out loud so they are no longer quiet?",
        "I need these letters to be vocalized - can you help by reading them aloud?",
        "Please give voice to this silent text by speaking the words.",
        "Could you turn this text into understandable speech by reading it out loud?",
        "Would you read these written words so that they can be heard?",
        "I require you to speak aloud the text on this page.",
        "Do me a favor and vocalize these letters into sounds.",
        "Can you translate these written words into audible speech for me?",
        "Please give audible voice to this text by reading it aloud.",
        "I need you to say these written phrases out loud.",
        "Would you utter these words vocally so that they can be heard?",
        "Could you articulate this text into understandable speech for me?",
        "It would help me if you could read these letters aloud into sounds.",
        "I would appreciate it if you vocalized this written text for me to hear.",
        "Is it possible for you to speak these words so they are no longer silent?",
        "Would you mind reading this text out loud so that it is audible?",
        "Can you verbalize these letters into understandable speech?",
        "Please translate this written text into spoken words for me.",
        "I require you to give voice to these phrases by reading them aloud.",
        "Could you say these words out loud so they can be heard audibly?",
        "Would you kindly articulate this text into speech using your voice?",
        "Do me a favor by vocalizing these written words for me.",
        "Can you turn these letters into understandable spoken language?",
        "I need these phrases to be read aloud - can you speak them for me?",
        "Please translate these words from text into audible speech.",
        "I would appreciate it if you could give sound to this silent text.",
        "Would you utter these written words vocally so I can hear them?",
        "Could you verbalize this text into speech using your voice?",
        "Is it possible for you to read these letters aloud into understandable sounds?",
        "Would you mind vocally articulating these words for me?",
        "Can you speak this text out loud so it is no longer quiet?",
        "I require you to read these phrases aloud into audible speech.",
        "Please give voice to these mute letters by uttering them.",
        "Could you say these written words aloud so they can be heard?",
        "Would you transform this text into understandable spoken language?",
        "Do me a favor by reading these words out loud.",
        "Can you articulate these letters into speech using your voice?",
        "I need you to vocalize this text so I can hear it.",
        "Please translate these written phrases into understandable spoken words.",
        "I would appreciate it if you could speak these silent words aloud.",
        "Would you give sound to this text by reading it vocally?",
        "Could you say these letters out loud so they become audible?",
        "Is it possible for you to verbalize these words into speech?",
        "Would you mind reading this text aloud so it can be heard?",
        "Can you vocalize these written phrases for me?",
        "I require you to articulate this text into understandable spoken language.",
        "Please utter these letters aloud into audible sounds.",
        "Could you translate these words from text into speech by speaking them?",
        "Would you give voice to these mute phrases for me?",
        "Do me a favor and read this text out loud.",
        "Can you speak these letters so they are no longer silent?",
        "I need you to say these written words aloud audibly.",
        "Please articulate this text vocally so I can hear it.",
        "I would appreciate it if you could verbalize these words into understandable speech.",
        "Would you transform these phrases from text into spoken language?",
        "Could you vocalize these letters so they become sounds?",
        "Is it possible for you to utter this text aloud for me to hear?",
        "Would you mind reading these words vocally so they are audible?",
        "Can you give sound to this silent text by speaking it?",
        "I require you to verbalize these written phrases into speech.",
        "Please say these letters out loud into understandable language.",
        "Could you articulate these words aloud so they can be heard?",
        "Would you translate this text into speech by vocalizing it for me?",
        "Do me a favor and utter these mute phrases vocally.",
        "Can you read these written words aloud so they are no longer quiet?",
        "I need you to give voice to this text by speaking it.",
        "Please verbalize these letters into understandable audible speech.",
        "I would appreciate it if you could articulate these words into spoken language.",
        "Would you say these phrases out loud so they can be heard?",
        "Could you translate this text into speech by reading it vocally?",
        "Is it possible for you to speak these letters aloud into sounds?",
        "Would you mind vocalizing these written words for me to hear?",
        "Can you utter this silent text aloud into understandable speech?",
        "I require you to read these mute phrases so they become audible.",
        "Please give voice to these letters by articulating them.",
        "Could you say these words aloud so they are no longer quiet?",
        "Would you verbalize this text for me using your voice?",
        "Do me a favor and speak these written phrases out loud.",
        "Can you translate these letters into understandable audible speech?",
        "I need you to read this text aloud so I can hear it.",
        "Please vocalize these words so they are no longer silent.",
        "I would appreciate it if you could articulate these phrases into speech using your voice.",
        "Would you utter these letters into understandable spoken language?",
        "Could you give sound to this text by saying it out loud?",
        "Is it possible for you to speak these written words audibly?",
        "Would you mind verbalizing this text into speech for me to hear?",
        "Can you read these mute phrases aloud so they become sounds?",
        "I require you to translate these letters into understandable spoken words.",
        "Please say this text aloud so it is no longer quiet.",
        "Could you vocalize these written words using your voice?",
        "Would you articulate these phrases into audible speech for me?",
        "Do me a favor and utter this text vocally so it can be heard.",
        "Can you give voice to these silent letters by speaking them?",
        "I need you to verbalize these words into understandable language.",
        "Please read this text out loud so I can hear it.",
        "I would appreciate it if you could speak these mute phrases aloud.",
        "Would you translate these written letters into speech vocally?",
        "Could you say these words out loud so they are audible?",
        "Is it possible for you to articulate this text into understandable spoken sounds?",
        "Would you mind reading these phrases aloud so they can be heard?",
        "Can you vocalize these silent letters for me?",
        "I require you to speak this text so it is no longer quiet.",
        "Please utter these written words into audible speech.",
        "Could you give voice to these phrases by articulating them?",
        "Would you verbalize these letters into understandable spoken language for me?",
        "Do me a favor and say this text out loud audibly.",
        "Can you translate these mute words into speech using your voice?",
        "I need you to read these phrases aloud so they can be heard.",
        "Please speak these silent letters into understandable sounds.",
        "I would appreciate it if you could articulate this text vocally for me.",
        "Would you utter these written words into audible speech?",
        "Could you verbalize these phrases into understandable spoken language?",
        "Is it possible for you to give voice to this text by reading it aloud?",
        "Would you mind saying these mute letters so they become sounds?",
        "Can you speak these words so they are no longer silent?",
        "I require you to articulate this text into speech audibly.",
        "Please translate these written phrases into understandable spoken language for me.",
        "Could you read these silent letters aloud so I can hear them?",
        "Would you vocalize these words using your voice so they are audible?",
        "Do me a favor and give sound to this text by uttering it.",
        "Can you say these mute phrases out loud into speech?",
        "I need you to verbalize this written text so it can be heard.",
        "Please articulate these letters into understandable spoken words.",
        "I would appreciate it if you could speak this text aloud so it is no longer quiet.",
        "Would you translate these phrases into audible speech by reading them vocally?",
        "Could you utter these written words for me to hear?",
        "Is it possible for you to give voice to these mute letters?",
        "Would you mind articulating this text into understandable spoken language?",
        "Can you say these silent words aloud so they become audible?",
        "I require you to read these phrases vocally so I can hear them.",
        "Please verbalize this text into speech using your voice.",
        "Could you speak these letters out loud so they are no longer mute?",
        "Would you translate these written words into understandable audible language for me?",
        "Do me a favor and vocalize these phrases so they can be heard.",
        "Can you utter this silent text into speech by articulating it?",
        "I need you to give voice to these letters by saying them aloud.",
        "Please read these words so they are no longer quiet.",
        "I would appreciate it if you could articulate these phrases vocally into understandable speech.",
        "Would you speak this text aloud audibly using your voice?",
        "Could you verbalize these mute letters into sounds?",
        "Is it possible for you to translate these written words into audible spoken language?",
        "Would you mind vocalizing these phrases for me to hear?",
        "Can you utter this text so it is no longer silent?",
        "I require you to speak these letters into understandable speech.",
        "Please say these mute words aloud so they can be heard.",
        "Could you read this text vocally so it becomes audible?",
        "Would you give voice to these written phrases by articulating them into speech?",
        "Do me a favor and translate these silent letters into understandable spoken language.",
        "Can you verbalize these words so I can hear them?",
        "I need you to speak this text aloud into audible speech.",
        "Please utter these mute phrases using your voice.",
        "I would appreciate it if you could articulate these letters vocally into sounds.",
        "Would you say these written words out loud so they can be heard?",
        "Could you read this text for me so it is no longer silent?",
        "Is it possible for you to vocalize these phrases into understandable speech?",
        "I require you to translate these silent words into speech by speaking them.",
        "Please vocalize these phrases aloud so I can hear them.",
        "Could you utter this text vocally so it is no longer quiet?",
        "Would you give voice to these mute letters by reading them audibly?",
        "Do me a favor and articulate these words into understandable spoken language.",
        "Can you speak these silent phrases aloud so they can be heard?",
        "I need you to verbalize this mute text for me into audible speech.",
        "Please translate these quiet letters vocally into understandable sounds.",
        "I would appreciate it if you could say these words out loud so they are no longer silent.",
        "Would you read these mute phrases aloud so I can hear them?",
        "Could you utter this text into audible spoken language using your voice?",
        "Is it possible for you to articulate these quiet letters into speech?",
        "Would you mind speaking these silent words so they become understandable audible language?",
        "Can you give voice to these phrases by vocalizing them for me to hear?",
        "I require you to translate this mute text into speech by reading it aloud.",
        "Please say these quiet letters so they are no longer mute.",
        "Could you verbalize these words into understandable audible speech using your voice?",
        "Would you utter these silent phrases vocally so I can hear them?",
        "Do me a favor and articulate this text aloud into speech.",
        "Can you speak these mute letters so they become understandable sounds?",
        "I need you to read these quiet words vocally into audible language.",
        "Please give voice to these phrases by articulating them so I can hear.",
        "I would appreciate it if you could translate this silent text into understandable spoken speech.",
        "Would you say these mute letters aloud audibly?",
        "Could you verbalize these quiet words into language I can hear using your voice?",
        "Is it possible for you to utter these phrases vocally so they can be heard?",
        "Would you mind articulating this text into audible speech for me?",
        "Can you speak these letters so they are no longer silent?",
        "I require you to read these mute words into understandable spoken language.",
        "Please vocalize these quiet phrases aloud so I can hear them.",
        "Could you give voice to this text by translating it into audible speech?",
        "Would you articulate these letters so they become understandable sounds?",
        "Do me a favor and say these silent words out loud audibly.",
        "Can you utter these mute phrases using your voice so they can be heard?",
        "Convert this text into speech.",
        "Please read this text aloud.",
        "Transform this text into audible speech.",
        "Convert the given text into spoken words.",
        "Can you change this text into speech?",
        "Please, read this text aloud.",
        "Could you make this text talk?",
        "Translate this text into spoken language.",
        "Generate speech from this text.",
        "Transform text into an audible format.",
        "Make this text speak out loud.",
        "Speak this text for me."
    ],
    "image": [
        "What image comes to mind from this text?",
        "Create a visual interpretation of the following words.",
        "Transform these words into a picture.",
        "Depict the essence of this text visually.",
        "Craft an image that embodies this sentence.",
        "Envision this text as an image.",
        "Compose a picture that matches this description.",
        "Can you draw a scene based on this text?",
        "What picture do you see when you read these words?",
        "Convert this text into an illustrative format.",
        "What graphic representation matches this text?",
        "Turn these words into a graphic image.",
        "Design an image that reflects this text.",
        "Construct a visual narrative from this sentence.",
        "Render this text into a visual piece.",
        "Create an image that conveys this text's message.",
        "Illustrate this concept in image form.",
        "How would you visually translate this text?",
        "Develop a picture based on this textual description.",
        "Design a graphic that complements this text.",
        "What visual form would this text take?",
        "How would you graphically present this sentence?",
        "Craft a picture that tells this text's story.",
        "Can you visualize this text in an image?",
        "Produce an image that aligns with this text.",
        "How would you depict this text in a picture?",
        "Turn this textual description into an image.",
        "What image best represents this text?",
        "Conjure an image that encapsulates this text.",
        "Create a visual that mirrors this text.",
        "Depict the narrative told in this text.",
        "How would you visually express this text?",
        "Imagine an image that reflects this sentence.",
        "How would you draw out this text's meaning?",
        "Can you paint a picture with these words?",
        "Create an image that reflects the tone of this text.",
        "Convey the message of this text in an image.",
        "Create an image based on the given text.",
        "Illustrate the concept described in the text.",
        "Draw an image based on the text's description.",
        "Generate an image according to the text.",
        "Can you imagine a visual representation of the contents of the text?",
        "Visualize the text for us.",
        "Can you come up with an image to represent the text?",
        "Make an image that corresponds to the text.",
        "Come up with an image that reflects the text's message.",
        "Is it possible to imagine a picture corresponding to the text?",
        "Could you sketch an image to describe the text?",
        "Can you turn the text into an image?",
        "Picture the text for us.",
        "How can you make a visual interpretation of the text?",
        "Put the description of the text into an image.",
        "Could you design a visual representation of the text?",
        "Generate an image that brings the text to life.",
        "Could you put the text into an image?",
        "Generate an image that captures the essence of the text.",
        "Design an image that conveys the meaning of the text.",
        "Could you come up with an image based on the text?",
        "Develop a visual interpretation of the text.",
        "Construct an image based on the text's content.",
        "Can you make a visual image based on the text?",
        "Craft an image that conveys the message of the text.",
        "Can you create a picture from the information in the text?",
        "Invent an image for the text.",
        "Can you imagine a visual representation of the text?",
        "Make an image that corresponds to the text.",
        "Can you construct a picture based on the text?",
        "Come up with a visual image to illustrate the text.",
        "Produce an image that represents the content of the text.",
        "Design a visual image for the text.",
        "Compose an image that reflects the meaning of the text.",
        "Make a picture to represent the contents of the text.",
        "Could you make a drawing to portray the text?",
        "Could you devise a visual image that illustrates the text?",
        "Can you devise a graphic that captures the text?",
        "Design an image that captures the spirit of the text.",
        "Imagine a visual image that expresses the text.",
        "Develop a visual image that corresponds to the text.",
        "Could you come up with a picture that shares the meaning of the text?",
        "Put the text into an image that reflects the text.",
        "Construct a graphic that conveys the meaning of the text.",
        "Is it possible to make a picture that captures the content of the text?",
        "Could you think of an image to represent the text?",
        "Make an illustration for the text.",
        "Invent an image that portrays the message of the text.",
        "Construct a visual image that conveys the contents of the text.",
        "Could you make a graphic that demonstrates the text?",
        "Picture the contents of the text for us.",
        "Could you develop a visual that describes the text?",
        "Could you make a picture that expresses the text?",
        "Can you envision an image that communicates the text?",
        "Create a graphic that captures the spirit of the text.",
        "Put the description into an image.",
        "Devise a visual image that reflects the contents of the text.",
        "Construct an image to illustrate the text.",
        "Could you generate a picture that illustrates the text?",
        "Can you come up with a visual representation of the text's concept?",
        "Can you create an image that conveys the message of the text?",
        "Could you make a graphic that expresses the text?",
        "Come up with a picture that shares the message of the text.",
        "Make a visual image that reflects the text.",
        "Could you produce a visual representation of the text?",
        "Generate a picture that portrays the concept of the text.",
        "Can you make an image to describe the text?",
        "Construct a graphic that illustrates the text.",
        "Make a picture that reflects the message of the text.",
        "Can you come up with an image that shares the contents of the text?",
        "Can you invent an illustration for the text?",
        "Produce an image that conveys the concept of the text.",
    ],
    "music": [
        "Create a musical piece that captures the essence of this caption.",
        "Transform this caption into a musical journey.",
        "Use this caption as inspiration for your composition.",
        "Can you turn this caption into a melody?",
        "What emotions does this caption evoke for you? Create a musical response.",
        "Use this caption as the title for your musical piece.",
        "How would you translate this caption into a melody?",
        "Take elements from this caption and weave them into your musical composition.",
        "Use this caption as a springboard for your musical creativity.",
        "Allow this caption to guide your musical exploration.",
        "What musical techniques can you use to convey the message of this caption?",
        "Build a musical structure around the words of this caption.",
        "Use this caption as a starting point for your musical storytelling.",
        "Can you create a musical response to this caption?",
        "Let the words of this caption guide the rhythm of your composition.",
        "How can you incorporate the themes of this caption into your music?",
        "Use this caption as a foundation for your musical piece.",
        "How can you use the rhythm and flow of this caption in your music?",
        "Allow this caption to set the mood for your musical composition.",
        "What musical elements can you use to reflect the meaning of this caption?",
        "Let this caption inspire your musical interpretation.",
        "Build a musical landscape that mirrors the imagery of this caption.",
        "How can you convey the message of this caption through your music?",
        "Create a musical dialogue between the words of this caption.",
        "Let this caption guide the melody and harmony of your piece.",
        "How does this caption make you feel? Translate those emotions into your music.",
        "Use the structure of this caption as a framework for your musical composition.",
        "Can you create a musical journey using the words of this caption?",
        "What musical techniques can you use to convey the tone of this caption?",
        "Begin your composition with the words of this caption in mind.",
        "Use this caption to craft a musical narrative.",
        "Let this caption inspire the tempo and rhythm of your musical creation.",
        "Can you create a musical translation of this caption?",
        "Use this caption to shape the melody and harmony of your composition.",
        "How can you use the concept of contrast in your musical interpretation of this caption?",
        "Let the words of this caption guide the structure of your musical piece.",
        "Create a musical dialogue between the different elements of this caption.",
        "How can you use instrumentation to enhance the meaning of this caption?",
        "Let this caption inspire the mood and atmosphere of your musical composition.",
        "Use this caption as a starting point for your musical improvisation.",
        "How does this caption inspire your musical imagination?",
        "Incorporate the themes of this caption into your musical variations.",
        "Allow this caption to guide the development of your musical piece.",
        "Can you use this caption as a lyrical inspiration for your musical composition?",
        "Use the words of this caption to create a musical dialogue between different instruments.",
        "How can you use different musical genres to interpret this caption?",
        "Create a musical response to the emotions evoked by this caption.",
        "Use this caption as a foundation for your musical storytelling.",
        "How can you use musical motifs to represent the different elements of this caption?",
        "Let the words of this caption inspire the structure and form of your musical piece.",
        "Use this caption as a guide to explore different musical textures and timbres.",
        "How can you incorporate the concept of tone painting into your musical interpretation of this caption?",
        "Let this caption guide the dynamics and pacing of your musical composition.",
        "What musical techniques can you use to convey the message of this caption?",
        "Create a musical journey that reflects the imagery and themes of this caption.",
        "Use this caption to guide your musical development and transitions.",
        "Let the words of this caption inspire your choice of musical structure and form.",
        "Use this caption as inspiration for a musical call and response.",
        "Incorporate elements from this caption into your musical improvisation.",
        "Use this caption to create a musical dialogue between different rhythms and melodies.",
        "How does this caption inspire your musical creativity?",
        "Allow the words of this caption to inspire your choice of musical key and mode.",
        "What musical elements can you use to represent the different scenes or images in this caption?",
        "Let the rhythm and flow of this caption guide your musical composition.",
        "Use the concepts of contrast and repetition to highlight the meaning of this caption in your music.",
        "How can you use silence and space to enhance the mood and atmosphere of your musical interpretation of this caption?",
        "Allow this caption to guide the development and flow of your musical piece.",
        "Use this caption as a foundation for your musical storytelling.",
        "Use the words of this caption as a starting point for your musical composition.",
        "Let the structure of this caption inspire the structure and form of your musical piece.",
        "Use this caption to create a musical exploration of different themes and emotions.",
        "How can you use instrumentation and orchestration to convey the meaning of this caption?",
        "Let the words of this caption inspire the melodies and harmonies in your piece.",
        "Use this caption as a guide to explore different musical techniques and styles.",
        "How can you use the concept of musical tension to amp up the emotions of this caption in your composition?",
        "Create a musical response to the imagery and themes in this caption.",
        "Use this caption as a springboard for your musical creativity.",
        "How can you use the concept of musical motifs to represent the different elements in this caption?",
        "Use the words of this caption as inspiration for your musical improvisation.",
        "Let this caption guide the dynamics and pacing of your musical composition.",
        "What musical techniques can you use to convey the tone and mood of this caption?",
        "Incorporate elements from this caption into your musical variations.",
        "Use this caption as a starting point for your musical storytelling.",
        "How can you use different musical genres to interpret the emotions and meaning of this caption?",
        "Use the structure of this caption to create a musical journey.",
        "Let the words of this caption inspire the rhythm and flow of your composition.",
        "Use this caption as a springboard for your musical development and transitions.",
        "How does this caption inspire your musical imagination?",
        "Create a musical interpretation of this caption that captures its essence.",
    ],
    "audio": [
        "Develop a sound with the given text.",
        "Incorporate sonorities from the text into an audio.",
        "Create a soundscape based on the provided text.",
        "Formulate a comprehensive sound using the words in this text.",
        "Implement an audio from the written material.",
        "Generate a soundscape of this text.",
        "Can you generate a sound from this passage?",
        "Compose a novel audio out of this content.",
        "Would you be able to make a sound from the text?",
        "Compile an audio indulging the written text.",
        "Do you think you can arrange a sound from the text?",
        "Generate a sound made from the text.",
        "Design a sound that doubles the text.",
        "Make an audio with this text as a source.",
        "Compose a new audio based on this text.",
        "Is it possible to form a sound utilizing this text?",
        "Could you conjure a sound under the influence of this text?",
        "Come up with a sound with this text as its foundation.",
        "Develop an audio rooted in the information provided.",
        "Are you able to craft a sound dependent on the text?",
        "Could you assemble a sound that reflects the given text?",
        "Create an aural interpretation from the content.",
        "Make a sweeping soundscape with the words in it.",
        "Do you think you can construct a sound out of this passage?",
        "Formulate a captivating soundscape of the text.",
        "Generate a truly immersive sound for the source.",
        "Design a soundscape which is based on the text.",
        "Construct the kind of sound from this text which would accompany an ocean wave rolling in.",
        "Create a quivering sound due to the text.",
        "Come up with a soothing audio with words intertwined in it.",
        "Design a sound relying heavily on the content itself.",
        "Make a ringing sound relevant to the text.",
        "Is it possible to devise a soothing and lush soundscape from the text?",
        "Generate a sweet soundscape from the provided words.",
        "Develop a hypnotic sound induced by this text.",
        "Synthesize a sweeping sound based on the written material.",
        "Could you make a powerful sound which reflects the words in the text?",
        "Extract a properly paced sound from the written material.",
        "Compose a beautiful sound that includes the provided text.",
        "Develop an acoustic out of this text.",
        "Could you generate a sound which expresses the given text?",
        "Create a vibrant audio of the material provided.",
        "Make an audio of passionate intensity with the given text.",
        "Generate an audio which is based on the stories written within the text.",
        "Can you compile a soundscape of the words in the passage?",
        "Could you make a sound that moves along with the information given?",
        "Manufacture a sound that comprehends this text.",
        "Make a sound containing the different elements of the text.",
        "Develop an audio which displays the text in a different form.",
        "Can you design a soundscape using the words in the passage?",
        "Construct a different sound out of the words in this text.",
        "Is it possible to create a sound that emphasizes the text's emotion?",
        "Arrange a sound that showcases its connection to the text.",
        "Can you compile an atmospheric audio that is reflective of the text?",
        "Develop a sound that could invite a reader's imagination.",
        "Fabricate a soundscaping of the text as a whole.",
        "Make a sound that illuminates the text with an engaging tone.",
        "Generate an audio that offers a unique interpretation of the text.",
    ]
}
